[build]
  publish = "/"  # Deploy လုပ်မယ့် Directory (Root)
  command = ""   # Build Command မလိုအပ်
  functions = "functions"  # Functions Directory

[dev]
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
