[build]
  publish = "."
[functions]
  directory = "functions"
  node_bundler = "esbuild"
[dev]
  framework = "#static"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[context.production.environment]
  NODE_VERSION = "16"  # Updated to a more recent version
